twig:
    default_path: '%kernel.project_dir%/templates'
    file_name_pattern: '*.twig'
    form_themes:
        - 'form/bulma_form_theme.html.twig'
    cache: false
    
when@test:
    twig:
        strict_variables: true
